name: Validate customers

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    strategy:
      fail-fast: false
      matrix:
        customer_key:
          - demo-a
          - demo-b
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      customer_key: ${{ matrix.customer_key }}
